annotations <- read.csv("C:/Users/Lynxa/Desktop/Doctorals/Latvian tweets/all_annotations_counts9.txt", header=FALSE, sep="\t")
a <- as.data.frame(annotations)
a$V2 <- as.numeric(as.character(a$V2))
a$V3 <- as.numeric(as.character(a$V3))
a$V4 <- as.numeric(as.character(a$V4))
a$V5 <- as.numeric(as.character(a$V5))
a$V6 <- as.numeric(as.character(a$V6))
a$V7 <- as.numeric(as.character(a$V7))
a$V8 <- as.numeric(as.character(a$V8))
a$V9 <- as.double(as.character(a$V9))
a$V10 <- as.numeric(as.character(a$V10))
a$V11 <- as.numeric(as.character(a$V11))
a$V12 <- as.double(as.character(a$V12))
a$V13 <- as.numeric(as.character(a$V13))
a$V14 <- as.numeric(as.character(a$V14))
a$V15 <- as.double(as.character(a$V15))
a$V16 <- as.numeric(as.character(a$V16))
a$V17 <- as.numeric(as.character(a$V17))
a$V18 <- as.double(as.character(a$V18))
a$V19 <- as.numeric(as.character(a$V19))
a$V20 <- as.numeric(as.character(a$V20))
a$V21 <- as.numeric(as.character(a$V21))
a$V22 <- as.double(as.character(a$V22))
a$V23 <- as.numeric(as.character(a$V23))
a$V24 <- as.numeric(as.character(a$V24))
a$V25 <- as.double(as.character(a$V25))
a$V26 <- as.numeric(as.character(a$V26))
a$V27 <- as.numeric(as.character(a$V27))
a$V28 <- as.double(as.character(a$V28))
a$V29 <- as.numeric(as.character(a$V29))
a$V30 <- as.numeric(as.character(a$V30))
a$V31 <- as.numeric(as.character(a$V31))


b <- a[!is.na(a$V2)&!is.na(a$V3)&!is.na(a$V4),c(2,3,4)]
b2 <-a[is.na(a$V2)&!is.na(a$V3)&!is.na(a$V4)&!is.na(a$V5),c(5,3,4)]
names(b2)<- names(b)
b <- rbind(b,b2)
row_means <- apply(X=b, MARGIN=1, FUN=mean, na.rm=TRUE)
row_meds <- apply(X=b, MARGIN=1, FUN=median, na.rm=TRUE)
b <- cbind (b, row_means)
b <- cbind(b, row_meds)
c<-a[!is.na(a$V2)&!is.na(a$V3)&!is.na(a$V4),c(6:31)]
c2 <- a[is.na(a$V2)&!is.na(a$V3)&!is.na(a$V4)&!is.na(a$V5),c(6:31)]
names(c2)<- names(c)
b <-cbind(b,rbind(c,c2))
colnames(b) <-c("1st", "2nd", "3d", 'Avg', 'Median', 'Upper', 'UpperN','Ex', 'ExN', 'Qu','QuN','Dot','DotN', 'Com', 'ComN', "Quo", "QuoN", "MulA",'Emo',
                'EmoBool', 'Emopos', 'countEmoNeg', 'countEmoNeu', 'countEmoNegNeu', 'EmoHPos', 'EmoHNeg','Hash','HashBool','Picture','PTaC','len')

cor(b)
